/**
 * Reads google-font-metadata and outputs a static TypeScript file
 * with curated popular Google Font families and their categories.
 *
 * Usage: bun run scripts/generate-font-list.ts
 */
import { APIv2 } from 'google-font-metadata';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const POPULAR_FONTS: string[] = [
	'ABeeZee',
	'Abril Fatface',
	'Alegreya',
	'Alegreya Sans',
	'Alfa Slab One',
	'Amatic SC',
	'Archivo',
	'Archivo Narrow',
	'Arimo',
	'Arvo',
	'Asap',
	'Assistant',
	'Bangers',
	'Barlow',
	'Barlow Condensed',
	'Bebas Neue',
	'Bitter',
	'Bree Serif',
	'Cabin',
	'Cairo',
	'Catamaran',
	'Caveat',
	'Comfortaa',
	'Cormorant Garamond',
	'Crimson Text',
	'DM Sans',
	'DM Serif Display',
	'Dancing Script',
	'Domine',
	'Dosis',
	'EB Garamond',
	'Exo 2',
	'Fira Sans',
	'Fira Sans Condensed',
	'Fredoka',
	'Geologica',
	'Great Vibes',
	'Heebo',
	'Hind',
	'IBM Plex Mono',
	'IBM Plex Sans',
	'IBM Plex Serif',
	'Inconsolata',
	'Inter',
	'Josefin Sans',
	'Josefin Slab',
	'Kalam',
	'Kanit',
	'Karla',
	'Lato',
	'Lexend',
	'Libre Baskerville',
	'Libre Franklin',
	'Lilita One',
	'Lobster',
	'Lora',
	'Merriweather',
	'Merriweather Sans',
	'Montserrat',
	'Mukta',
	'Mulish',
	'Neuton',
	'Noticia Text',
	'Noto Sans',
	'Noto Serif',
	'Nunito',
	'Nunito Sans',
	'Old Standard TT',
	'Open Sans',
	'Orbitron',
	'Oswald',
	'Outfit',
	'Overpass',
	'PT Sans',
	'PT Serif',
	'Pacifico',
	'Permanent Marker',
	'Playfair Display',
	'Poppins',
	'Quicksand',
	'Rajdhani',
	'Raleway',
	'Roboto',
	'Roboto Condensed',
	'Roboto Mono',
	'Roboto Slab',
	'Rubik',
	'Sacramento',
	'Satisfy',
	'Shadows Into Light',
	'Signika',
	'Slabo 27px',
	'Source Code Pro',
	'Source Sans 3',
	'Source Serif 4',
	'Space Grotesk',
	'Space Mono',
	'Spectral',
	'Teko',
	'Titillium Web',
	'Ubuntu',
	'Varela Round',
	'Work Sans',
	'Yanone Kaffeesatz',
	'Zilla Slab'
];

interface FontEntry {
	family: string;
	category: string;
}

const apiLookup = new Map(
	Object.values(APIv2).map((font: any) => [font.family as string, font.category as string])
);

const fonts: FontEntry[] = [];
for (const name of POPULAR_FONTS) {
	const category = apiLookup.get(name);
	if (category) {
		fonts.push({ family: name, category });
	} else {
		console.warn(`⚠ Font not found in APIv2: "${name}"`);
	}
}

fonts.sort((a, b) => a.family.localeCompare(b.family));

const output = `// Auto-generated by scripts/generate-font-list.ts — do not edit manually
export interface GoogleFont {
	family: string;
	category: string;
}

export const googleFonts: GoogleFont[] = ${JSON.stringify(fonts)};
`;

const outPath = resolve(__dirname, '../src/lib/data/google-fonts.ts');
writeFileSync(outPath, output, 'utf-8');
console.log(`Wrote ${fonts.length} fonts to ${outPath}`);
